server:
  port: 8081
logging:
  level:
    org:
      springframework:
        data: debug
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/nominaDB
springdoc:
  swagger-ui:
    path: /api-doc.html
